# Generated by Django 5.1.2 on 2024-10-24 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASTNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('operator', 'Operator'), ('operand', 'Operand')], max_length=10)),
                ('operator', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR'), ('>', 'Greater than'), ('<', 'Less than'), ('=', 'Equal to')], max_length=10, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_child', to='rule_engine.astnode')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_child', to='rule_engine.astnode')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule_engine.astnode')),
            ],
        ),
    ]
