# Generated by Django 5.1.2 on 2024-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_alter_astnode_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='root',
        ),
        migrations.AddField(
            model_name='rule',
            name='rule_string',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
